// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Address struct {
	Receiver string `json:"receiver"`
	Address  string `json:"address"`
	Detail   string `json:"detail"`
	PinCode  string `json:"pinCode"`
	Tel      string `json:"tel"`
	Request  string `json:"request"`
}

type AddressBook struct {
	ID        string   `json:"_id"`
	IsDefault bool     `json:"isDefault"`
	Address   *Address `json:"address"`
}

type NewAddress struct {
	Receiver string `json:"receiver"`
	Address  string `json:"address"`
	Detail   string `json:"detail"`
	PinCode  string `json:"pinCode"`
	Tel      string `json:"tel"`
	Request  string `json:"request"`
}

type NewAddressBook struct {
	IsDefault bool        `json:"isDefault"`
	Address   *NewAddress `json:"address"`
}

type NewProduct struct {
	ProductID string `json:"productID"`
	Count     int    `json:"count"`
}

type NewProductInfo struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	PerAmount   int    `json:"perAmount"`
	ImgURL      string `json:"imgUrl"`
}

type NewService struct {
	State    int                  `json:"state"`
	Products []*NewServiceProduct `json:"products"`
}

type NewServiceProduct struct {
	ProductID string `json:"productID"`
	Count     int    `json:"count"`
}

type NewUser struct {
	Name  string `json:"name"`
	Age   int    `json:"age"`
	Phone string `json:"phone"`
}

type Product struct {
	Count   int          `json:"count"`
	Product *ProductInfo `json:"product"`
}

type ProductInfo struct {
	ProductID   string `json:"productID"`
	Name        string `json:"name"`
	Description string `json:"description"`
	PerAmount   int    `json:"perAmount"`
	ImgURL      string `json:"imgUrl"`
}

type Service struct {
	ID       string            `json:"_id"`
	Products []*ServiceProduct `json:"products"`
	State    int               `json:"state"`
}

type ServiceProduct struct {
	Product *ProductInfo `json:"product"`
	Count   int          `json:"count"`
}

type User struct {
	ID    string `json:"_id"`
	Name  string `json:"name"`
	Age   int    `json:"age"`
	Phone string `json:"phone"`
}
